FROM python:3.6
RUN apt-get update -y && apt-get install -y -q apt-utils && apt-get install -q -y git vim mc byobu w3m nmap mysql-common && apt-get clean && rm -rf /var/lib/apt/lists/*_*

RUN mkdir /code
WORKDIR /code
RUN pip install --upgrade pip
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/

# Quitar si lo gestiona docker-compose
# CMD ["python3","inventario.py"]
