version: '2'

services:
  registry-srv:
    image: registry:latest
    restart: unless-stopped
    ports:
      - 5001:5000
    volumes:
      - ./registry/storage:/var/lib/registry
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
    container_name: registry-srv

#  registry-ui: # Anda mal el ui. Usar 
#    image: joxit/docker-registry-ui:static
#    restart: always
#    ports:
#      - 3000:80
#    environment:
#      - REGISTRY_URL=http://hub.supercanal.tv:5001
#      - DELETE_IMAGES=true
##    container_name: registry-ui
